"""
XP/Leveling Cog - Handles XP gain from messages, reactions, and voice.
Uses XpService for database operations.
"""

import discord
import datetime
from random import randint
from discord.ext import commands, tasks

from config import BOT_CHANNEL_ID, XP_CONFIG, BATCH_UPDATE_INTERVAL
from services.xp_service import xp_service
from utils.embeds import create_leaderboard_embed, create_rank_embed


class XpCog(commands.Cog, name="Leveling"):
    """XP and Leveling system for the server."""
    
    def __init__(self, bot: commands.Bot):
        self.bot = bot
        
        # Spam prevention caches
        self.gained_msg_xp = set()           # Users who gained XP this cycle
        self.pending_xp = {}                  # Batched XP updates
        
        # Reaction XP tracking
        # Key: message_id -> total XP generated by that message
        self.message_reaction_xp = {}
        # Key: (user_id, message_id) -> bool (has user reacted to this msg?)
        self.user_reacted_to_message = set()
        # Key: user_id -> {'date': str, 'xp': int}
        self.daily_reaction_cache = {}
        
        # Start background task
        self.batch_update_db.start()
    
    def cog_unload(self):
        """Cleanup when cog is unloaded."""
        self.batch_update_db.cancel()
    
    # ─────────────────────────────────────────────────────────────────────
    # Background Task - Batch XP Updates
    # ─────────────────────────────────────────────────────────────────────
    
    @tasks.loop(seconds=BATCH_UPDATE_INTERVAL)
    async def batch_update_db(self):
        """Process pending XP and award voice XP."""
        # Reset message XP spam prevention
        self.gained_msg_xp.clear()
        
        # Clear large caches to prevent memory bloat
        if len(self.message_reaction_xp) > 10000:
            self.message_reaction_xp.clear()
        if len(self.user_reacted_to_message) > 50000:
            self.user_reacted_to_message.clear()
        
        # Award voice XP
        await self._process_voice_xp()
        
        # Batch save to database
        if self.pending_xp:
            print(f'[XP] Saving data for {len(self.pending_xp)} users...')
            await xp_service.batch_update(self.pending_xp.copy())
            self.pending_xp.clear()
            print('[XP] Data saved successfully')
    
    @batch_update_db.before_loop
    async def before_batch_update(self):
        """Wait for bot to be ready before starting loop."""
        await self.bot.wait_until_ready()
    
    async def _process_voice_xp(self):
        """Award XP to active voice channel participants."""
        if not self.bot.guilds:
            return
        
        guild = self.bot.guilds[0]
        afk_channel = guild.afk_channel
        voice_config = XP_CONFIG["voice"]
        
        for vc in guild.voice_channels:
            # Skip AFK channel
            if afk_channel and vc.id == afk_channel.id:
                continue
            
            # Filter valid members (not muted, not deafened, not bots)
            valid_members = [
                member for member in vc.members
                if not member.bot
                and not member.voice.mute
                and not member.voice.self_mute
                and not member.voice.deaf
                and not member.voice.self_deaf
                and not member.voice.suppress
            ]
            
            # Require minimum members
            if len(valid_members) >= voice_config["min_members"]:
                for member in valid_members:
                    self.pending_xp[member.id] = (
                        self.pending_xp.get(member.id, 0) + 
                        voice_config["xp_per_cycle"]
                    )
    
    # ─────────────────────────────────────────────────────────────────────
    # Event Listeners
    # ─────────────────────────────────────────────────────────────────────
    
    @commands.Cog.listener()
    async def on_message(self, message: discord.Message):
        """Award XP for messages (with spam prevention)."""
        # Ignore bots
        if message.author.bot:
            return
        
        msg_config = XP_CONFIG["message"]
        
        # Ignore short messages
        if len(message.content) < msg_config["min_length"]:
            return
        
        # Ignore bot command channels
        if message.channel.id == BOT_CHANNEL_ID:
            return
        
        user_id = message.author.id
        
        # Spam prevention: one XP gain per cycle
        if user_id not in self.gained_msg_xp:
            self.gained_msg_xp.add(user_id)
            xp_amount = randint(msg_config["min_xp"], msg_config["max_xp"])
            self.pending_xp[user_id] = self.pending_xp.get(user_id, 0) + xp_amount
    
    @commands.Cog.listener()
    async def on_reaction_add(self, reaction: discord.Reaction, user: discord.User):
        """
        Award XP for reactions.
        
        Rules:
        - A message can only generate up to 50 XP total from reactions
        - A user can only gain XP once per message (for their first reaction)
        - Users have a daily cap of 100 XP from reactions
        """
        if user.bot:
            return
        
        react_config = XP_CONFIG["reaction"]
        msg_id = reaction.message.id
        user_id = user.id
        today = str(datetime.date.today())
        
        # Check 1: Has user already reacted to this message?
        reaction_key = (user_id, msg_id)
        if reaction_key in self.user_reacted_to_message:
            return  # Already gained XP from this message
        
        # Check 2: User's daily reaction XP cap
        user_daily = self.daily_reaction_cache.get(user_id, {'date': today, 'xp': 0})
        if user_daily['date'] != today:
            user_daily = {'date': today, 'xp': 0}
        
        if user_daily['xp'] >= react_config["daily_cap"]:
            return  # Daily cap reached
        
        # Check 3: Message's total reaction XP cap
        msg_total_xp = self.message_reaction_xp.get(msg_id, 0)
        if msg_total_xp >= react_config["max_xp_per_message"]:
            return  # Message cap reached
        
        # All checks passed - award XP
        xp_amount = react_config["xp_per_reaction"]
        
        # Update caches
        self.user_reacted_to_message.add(reaction_key)
        self.message_reaction_xp[msg_id] = msg_total_xp + xp_amount
        user_daily['xp'] += xp_amount
        self.daily_reaction_cache[user_id] = user_daily
        
        # Queue XP for batch update
        self.pending_xp[user_id] = self.pending_xp.get(user_id, 0) + xp_amount
    
    # ─────────────────────────────────────────────────────────────────────
    # Commands
    # ─────────────────────────────────────────────────────────────────────
    
    @commands.command(aliases=['lb', 'top'])
    async def leaderboard(self, ctx: commands.Context):
        """Show the server XP leaderboard."""
        top_users = await xp_service.get_leaderboard(limit=10)
        embed = create_leaderboard_embed(ctx.guild, top_users)
        await ctx.reply(embed=embed)
    
    @commands.command()
    async def rank(self, ctx: commands.Context, member: discord.Member = None):
        """Show your or another user's rank."""
        target = member or ctx.author
        rank, xp = await xp_service.get_rank(target.id)
        embed = create_rank_embed(target, rank, xp)
        await ctx.reply(embed=embed)


async def setup(bot: commands.Bot):
    """Load the XP cog."""
    await bot.add_cog(XpCog(bot))
